#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100 with FizzBuzz rules
# Requirements:
# - FizzBuzz for multiples of 3 and 5
# - Fizz for multiples of 3
# - Buzz for multiples of 5
# - Otherwise, display the number
# - Display in list format
## Instead of  "if [ $((count % 3)) -eq 0 ] && [ $((count % 5)) -eq 0 ]; we use the LCM which 15"
count=1

while [ $count -le 100 ]; do
    if [ $((count % 15)) -eq 0 ]; then
        echo "FizzBuzz"
    elif [ $((count % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((count % 5)) -eq 0 ]; then
        echo "Buzz"
    else
        echo "$count"
    fi
    count=$((count + 1))
done
